admin/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path

from rest_framework import routers


from .api.location import views as location_views
from .api.hike import views as hike_views
from . import views


app_name = "hikster-admin"

router = routers.SimpleRouter()

router.register("locations", location_views.LocationAdminViewSet)
router.register("trail-sections", hike_views.TrailSectionAdminViewSet)
router.register("trails", hike_views.TrailAdminViewSet)
router.register("point-of-interests", location_views.PoiAdminViewSet)


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="hikster-admin/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(next_page="/admin"), name="logout"),
    path(
        "<int:organization_id>/",
        include(
            [
                path("", views.OrganizationView.as_view(), name="organization"),
                path(
                    "locations/", views.LocationListView.as_view(), name="location-list"
                ),
                path(
                    "locations/<int:location_id>/",
                    views.LocationDetailView.as_view(),
                    name="location-detail",
                ),
                path(
                    "trail-sections/",
                    views.TrailSectionListView.as_view(),
                    name="trail-section-list",
                ),
                path(
                    "trail-sections/<int:trailsection_id>/",
                    views.TrailSectionDetailView.as_view(),
                    name="trail-section-detail",
                ),
                path(
                    "trail-sections/new/",
                    views.TrailSectionCreateView.as_view(),
                    name="trail-section-new",
                ),
                path("trails/", views.TrailListView.as_view(), name="trail-list"),
                path(
                    "trails/<int:trail_id>/",
                    views.TrailDetailView.as_view(),
                    name="trail-detail",
                ),
                path("trails/new/", views.TrailCreateView.as_view(), name="trail-new"),
                path("poi/", views.POIListView.as_view(), name="poi-list"),
                path("poi/new/", views.POICreateView.as_view(), name="poi-new"),
                path("poi/<int:poi_id>/", views.POIDetailView.as_view(), name="poi-detail"),
            ]
        ),
    ),
    path("api/", include(router.urls)),
]

urls.py
from django.contrib.gis import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path


urlpatterns = [
    path("", include("hikster.urls_website")),
    path("django-admin/", admin.site.urls),
    path("django-admin/rq/", include("django_rq.urls")),
    path("admin/", include("hikster.admin.urls")),
]

if settings.DEBUG:
    urlpatterns = (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns
    )

templates/hikster-admin/include/navbar.html
{% load i18n %}
{% load static from staticfiles %}

<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
  <a class="navbar-brand" href="{% url 'hikster-admin:index' %}">
    <img src="{% static 'img/Logo_128px_Green.png' %}" alt="" />
  </a>

  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" target="_blank" href="{% url 'toc' %}">
            {% trans "Terms of use" %}
        </a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'hikster-admin:logout' %}">
            {% trans "Logout" %}
        </a>
      </li>
      {% endif %}
  </div>
</nav>