admin/urls.py
from django.contrib.auth import views as auth_views
from django.urls import include, path

from rest_framework import routers


from .api.location import views as location_views
from .api.hike import views as hike_views
from . import views


app_name = "hikster-admin"

router = routers.SimpleRouter()

router.register("locations", location_views.LocationAdminViewSet)
router.register("trail-sections", hike_views.TrailSectionAdminViewSet)
router.register("trails", hike_views.TrailAdminViewSet)
router.register("point-of-interests", location_views.PoiAdminViewSet)


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="hikster-admin/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(next_page="/admin"), name="logout"),
    path(
        "<int:organization_id>/",
        include(
            [
                path("", views.OrganizationView.as_view(), name="organization"),
                path(
                    "locations/", views.LocationListView.as_view(), name="location-list"
                ),
                path(
                    "locations/<int:location_id>/",
                    views.LocationDetailView.as_view(),
                    name="location-detail",
                ),
                path(
                    "trail-sections/",
                    views.TrailSectionListView.as_view(),
                    name="trail-section-list",
                ),
                path(
                    "trail-sections/<int:trailsection_id>/",
                    views.TrailSectionDetailView.as_view(),
                    name="trail-section-detail",
                ),
                path(
                    "trail-sections/new/",
                    views.TrailSectionCreateView.as_view(),
                    name="trail-section-new",
                ),
                path("trails/", views.TrailListView.as_view(), name="trail-list"),
                path(
                    "trails/<int:trail_id>/",
                    views.TrailDetailView.as_view(),
                    name="trail-detail",
                ),
                path("trails/new/", views.TrailCreateView.as_view(), name="trail-new"),
                path("poi/", views.POIListView.as_view(), name="poi-list"),
                path("poi/new/", views.POICreateView.as_view(), name="poi-new"),
                path("poi/<int:poi_id>/", views.POIDetailView.as_view(), name="poi-detail"),
            ]
        ),
    ),
    path("api/", include(router.urls)),
]

urls.py
from django.contrib.gis import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path


urlpatterns = [
    path("", include("hikster.urls_website")),
    path("django-admin/", admin.site.urls),
    path("django-admin/rq/", include("django_rq.urls")),
    path("admin/", include("hikster.admin.urls")),
]

if settings.DEBUG:
    urlpatterns = (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlpatterns
    )

organizations/models.py
from django.conf import settings
from django.db import models

from hikster.hike.models import Trail, TrailSection
from django.utils import timezone
from django.utils.functional import cached_property
from hikster.utils.models import Address
from hikster.location.models import PointOfInterest


class OrganizationWidget(models.Model):
    organization = models.OneToOneField(
        "Organization", on_delete=models.CASCADE, related_name="widget"
    )
    max_widget_loads = models.IntegerField(default=0)
    max_page_loads = models.IntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.organization.name


class Organization(models.Model):
    name = models.CharField(max_length=128)
    contact = models.CharField(max_length=128, null=True, blank=True)
    address = models.OneToOneField(
        Address, null=True, blank=True, on_delete=models.CASCADE
    )
    aid = models.CharField(max_length=500, default=None, null=True, blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not hasattr(self, "widget"):
            OrganizationWidget.objects.create(organization=self)

    def get_location_shape_query(self):
        location_buffered_shapes = [
            location.shape.buffer(0.02)
            for location in self.locations.all()
            if location.shape is not None
        ]

        # Turn the list of location shapes into a list of Q objects
        queries = [models.Q(shape__within=shape) for shape in location_buffered_shapes]

        if not queries:
            return None

        # Take one Q object from the list
        query = queries.pop()
        # Or the Q object with the ones remaining in the list
        for item in queries:
            query |= item

        return query

    @property
    def trail_sections(self):
        query = self.get_location_shape_query()

        if query is None:
            return TrailSection.objects.none()

        return TrailSection.objects.filter(query)

    @property
    def point_of_interests(self):
        query = self.get_location_shape_query()

        if query is None:
            return PointOfInterest.objects.none()

        return PointOfInterest.objects.filter(query)

    @property
    def trails(self):
        return Trail.objects.filter(location__in=self.locations.all())

    @cached_property
    def total_widget_loads(self):
        return self.widget_loads.count()

    @cached_property
    def current_month_widget_loads(self):
        current_date = timezone.now().date()
        return self.widget_loads.filter(
            date_created__year=current_date.year, date_created__month=current_date.month
        ).count()

    @cached_property
    def total_page_loads(self):
        return self.page_loads.count()

    @cached_property
    def current_month_page_loads(self):
        current_date = timezone.now().date()
        return self.page_loads.filter(
            date_created__year=current_date.year, date_created__month=current_date.month
        ).count()

    @property
    def consumed_max_widget_loads(self):
        return self.current_month_widget_loads >= self.widget.max_widget_loads

    @property
    def consumed_max_page_loads(self):
        return self.current_month_page_loads >= self.widget.max_page_loads


class WidgetLoad(models.Model):
    organization = models.ForeignKey(
        "Organization", on_delete=models.CASCADE, related_name="widget_loads"
    )
    referrer = models.CharField(max_length=255, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.organization.name


class PageLoad(models.Model):
    organization = models.ForeignKey(
        "Organization", on_delete=models.CASCADE, related_name="page_loads"
    )
    widget_load = models.ForeignKey(
        "WidgetLoad", on_delete=models.CASCADE, related_name="page_loads"
    )
    referrer = models.CharField(max_length=255, blank=True)
    url = models.URLField(max_length=255, blank=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.organization.name


class OrganizationMember(models.Model):
    organization = models.ForeignKey(
        Organization, on_delete=models.CASCADE, related_name="members"
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("organization", "user")

    def __str__(self):
        return "{} -> {}".format(self.organization, self.user)

organizations/views.py
from rest_framework import permissions, status, views, viewsets
from rest_framework.response import Response

from .models import Organization
from .serializers import OrgWithUserSerializer, ValidateWidgetSerializer


class OrganizationViewSet(viewsets.ModelViewSet):
    queryset = Organization.objects.all()
    serializer_class = OrgWithUserSerializer

    def get_queryset(self):
        return self.queryset.filter(members__user=self.request.user)


class ValidateWidgetView(views.APIView):
    permission_classes = (permissions.AllowAny,)

    def post(self, request):
        serializer = ValidateWidgetSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        return Response(status=status.HTTP_200_OK)

templates/hikster-admin/base.html
{% load i18n %}
{% load static from staticfiles %}
<html>
  <head>
    <title>{% trans 'Hikster Admin' %}</title>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <style>
    @keyframes spin {
      0% { transform: rotate(0deg); }
      100% { transform: rotate(360deg); }
    }
    </style>
    {% block head_styles %}

    <link href="{% static 'css/pace.css' %}" rel="stylesheet" />
    <link href="{% static 'libs/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static 'hikster-admin/css/main.css' %}" rel="stylesheet" />
    <link href="{% static 'css/footer.css' %}" rel="stylesheet" />
    {% endblock %}

    {% block extra_styles %}
    {% endblock extra_styles %}

    {% include "settings.html" %}
  </head>
  <body>
    {% block body_before_container %}
    {% endblock body_before_container%}
    <div class="container-fluid admin-container">
      {% block body_container %}
      {% endblock body_container%}
    </div>

    {% include "website/footer.html" %}


    {% block js_before %}
    {% endblock js_before %}

    {% block body_js %}
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'libs/pace.min.js' %}"></script>
    <script src="{% static 'libs/bootstrap/js/bootstrap.min.js' %}"></script>
    {% endblock body_js %}

    {% block body_extra_js %}
    {% endblock body_extra_js %}
  </body>
</html>

templates/hikster-admin/base_authenticated.html
{% extends "hikster-admin/base_sidebar.html" %}
{% load i18n %}

{% block body_before_container %}
  {% include 'hikster-admin/include/navbar.html' %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      {% block breadcrumbs %}
        <li class="breadcrumb-item active">{% trans 'Hikster Admin' %}</li>
      {% endblock %}
    </ol>
  </nav>
{% endblock body_before_container %}

{% block body_container %}
  {% block content %}{% endblock %}
{% endblock body_container %}

templates/hikster-admin/base_sidebar_authenticated.html
{% extends "hikster-admin/base_authenticated.html" %}
{% load i18n %}

{% block breadcrumbs %}
  <li class="breadcrumb-item">
    <a href="{% url 'hikster-admin:index' %}">{% trans 'Hikster Admin' %}</a>
  </li>
  <li class="breadcrumb-item">{{ organization.name }}</li>
{% endblock %}

{% block body_container %}
  <div class="row mt-5">
    <div class="col-md-3 col-lg-2">
      {% block sidebar %}
        <ul class="nav flex-column nav-pills ul-sidebar">
          <li class="nav-item">
            <a class="nav-link{% if section == 'profile' %} active{% endif %}"
               href="{% url 'hikster-admin:organization' organization_id=organization.id %}">{% trans 'Profile'%}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link{% if section == 'location-list' %} active{% endif %}"
               href="{% url 'hikster-admin:location-list' organization_id=organization.id %}">{% trans 'Locations' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link{% if section == 'trail-sections' %} active{% endif %}"
               href="{% url 'hikster-admin:trail-section-list' organization_id=organization.id %}">{% trans 'Trail Sections' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link{% if section == 'trail-list' %} active{% endif %}"
               href="{% url 'hikster-admin:trail-list' organization_id=organization.id %}">{% trans 'Trails' %}</a>
          </li>
          <li class="nav-item">
              <a class="nav-link{% if section == 'poi-list' %} active{% endif %}"
                href="{% url 'hikster-admin:poi-list' organization_id=organization.id %}">{% trans 'Point of Interests' %}</a>
          </li>
        </ul>
      {% endblock sidebar %}
    </div>
    <div class="col-md-9 col-lg-10">
      {% block content %}Content{% endblock %}
    </div>
  </div>
{% endblock body_container %}

templates/hikster-admin/index.html
{% extends "hikster-admin/base_authenticated.html" %}
{% load i18n %}

{% block content %}
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <p>{% trans "Select the organization you would like to manage:" %}</p>
            <ul>
                {% for org in organizations %}
                    <li><a href="{% url 'hikster-admin:organization' organization_id=org.id %}">{{ org.name }}</a></li>
                {% empty %}
                    <li>{% trans "You do not have any organization." %}</li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}

templates/hikster-admin/poi-detail.html
{% extends 'hikster-admin/base_sidebar_authenticated.html' %}

{% load i18n %}
{% load static from staticfiles %}
{% load render_bundle from webpack_loader %}

{% block extra_styles %}
    <style>
    .map {
      width: 100%;
      height: 600px;
    }

    </style>
    <link rel="stylesheet" href="{% static 'libs/leaflet/dist/leaflet.css' %}" />
    <link rel="stylesheet" href="{% static 'libs/leaflet-draw/leaflet.draw.css' %}" />
    <link rel="stylesheet" href="{% static 'libs/leaflet-fullscreen/Control.FullScreen.css' %}" />
    <link rel="stylesheet" href="{% static 'css/map.css' %}" />
{% endblock extra_styles %}

{% block breadcrumbs %}
    <li class="breadcrumb-item">
        <a href="{% url 'hikster-admin:index' %}">{% trans 'Hikster Admin' %}</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'hikster-admin:organization' organization_id=organization.id%}">
            {{ organization.name }}
        </a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'hikster-admin:poi-list' organization_id=organization.id %}">
            {% trans "Point of Interests" %}
        </a>
    </li>
    <li class="breadcrumb-item">
        {% if poi %}
            {{ poi.name }}
        {% else %}
            {% trans "Create Point of Interest" %}
        {% endif %}
    </li>
{% endblock %}

{% block content %}

{{ graph|json_script:"graph_data" }}
{{ poi_data|json_script:"poi_data" }}
{{ poi_categories|json_script:"poi_categories" }}
{{ contact_types_data|json_script:"contact_types_data" }}
{{ other_pois_geojson|json_script:"other_pois_geojson" }}
{{ trail_sections_geojson|json_script:"trail_sections_geojson" }}
{{ location_geojson|json_script:"location_geojson_data" }}

<div id="poi-detail-component">
  <div class="row justify-content-center">
    <div class="col-12">
      <h1>
        {% if poi %}
          {% trans "Modify Poi" %}
        {% else %}
          {% trans "Create New Poi" %}
        {% endif %}
        <a
          href="{% url 'hikster-admin:poi-new' organization_id=organization.id %}"
          class="btn btn-success float-right"
        >
            {% trans "New" %}
        </a>
      </h1>


      <div v-show="getError('shape')" class="alert alert-danger alert-dismissible fade show d-none" role="alert">
          <strong>{% trans "Error" %}!</strong> {[ getError("shape") ]}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>

      <div v-show="successMessage" class="alert alert-success alert-dismissible fade show d-none" role="alert">
          {[ successMessage ]}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>

      <table class="table">
        <tbody>
          <tr>
            <th scope="row">{% trans "Name" %}</th>
            <td>
              <input
                :class="{ 'form-control': true, 'invalid': getError('name') }"
                type="text"
                v-model="poi.name"
                required
              />
              <div class="invalid-feedback">
                {[ getError("name") ]}
              </div>
            </td>
          </tr>

          <tr>
              <th scope="row">{% trans "Category" %}</th>
              <td>
                  <select
                    required
                    v-model="poi.category"
                    :class="{'form-control': true, 'invalid': getError('category')}"
                  >
                      <option v-for="category in categories" :value="category.id" :key="category.id">
                          {[ category.name ]}
                      </option>
                  </select>
                  <div class="invalid-feedback">
                      {[ getError("category") ]}
                  </div>
              </td>
          </tr>

          <tr>
              <th scope="row">{% trans "Type" %}</th>
              <td>
                  <select
                    required
                    v-model="poi.type"
                    :class="{'form-control': true, 'invalid': getError('type')}"
                  >
                      <option v-for="type in typeChoices" :value="type.id" :key="type.id">
                          {[ type.name ]}
                      </option>
                  </select>
                  <div class="invalid-feedback">
                      {[ getError("type") ]}
                  </div>
              </td>
          </tr>

          <tr>
              <td>{% trans "Description" %}</td>
              <td>
                  <ckeditor :editor="editor" v-model="poi.description" :config="editorConfig"></ckeditor>
              </td>
          </tr>

          <tr>
            <td>{% trans "Price" %}</td>
            <td>
              <ckeditor :editor="editor" v-model="poi.fare" :config="editorConfig"></ckeditor>
            </td>
          </tr>

          <tr>
            <td>{% trans "Street name" %}</td>
            <td>
              <input
                class="form-control"
                type="text"
                v-model="poi.address.street_name"
              />
            </td>
          </tr>
          <tr>
            <td>{% trans "Apartment" %}</td>
            <td>
              <input
                class="form-control"
                type="text"
                v-model="poi.address.apartment"
              />
            </td>
          </tr>
          <tr>
            <td>{% trans "City" %}</td>
            <td>
              <input
                class="form-control"
                type="text"
                v-model="poi.address.city"
              />
            </td>
          </tr>
          <tr>
            <td>{% trans "Province" %}</td>
            <td>
              <input
                class="form-control"
                type="text"
                v-model="poi.address.province"
              />
            </td>
          </tr>
          <tr>
            <td>{% trans "Postal code" %}</td>
            <td>
              <input
                class="form-control"
                type="text"
                v-model="poi.address.postal_code"
              />
            </td>
          </tr>
          <tr>
            <td>{% trans "Po box" %}</td>
            <td>
              <input
                class="form-control"
                type="text"
                v-model="poi.address.po_box"
              />
            </td>
          </tr>
          <tr>
            <td>{% trans "Country" %}</td>
            <td>
              <input
                class="form-control"
                type="text"
                v-model="poi.address.country"
              />
            </td>
          </tr>
          <tr>
              <td>{% trans "Contact" %}</td>
              <td>
                  <div class="form-row py-1" v-for="(contact, idx) in poi.contact" :key="idx">
                      <div class="col-auto">
                          <label class="col-form-label" :for="'contact' + idx">{% trans "Type" %}</label>
                      </div>
                      <div class="col-auto">
                          <select :id="'contact' + idx" v-model="contact.type" class="form-control">
                              <option v-for="type in contactTypes" :value="type[0]" :key="type[0]">
                                  {[ type[1] ]}
                              </option>
                          </select>
                      </div>
                      <div class="col-auto">
                          <label class="col-form-label" >{% trans "Value" %}</label>
                      </div>
                      <div class="col-auto">
                          <input
                            class="form-control"
                            type="text"
                            v-model="contact.value"
                          />
                      </div>
                      <div v-if="idx === poi.contact.length - 1" class="col-auto d-flex align-items-center">
                          <span @click="addContact" >
                              <hk-plus-icon class="add-icon"></hk-plus-icon>
                          </span>
                      </div>
                      <div v-else class="col-auto d-flex align-items-center">
                          <span @click="removeContact(idx)">
                            <hk-times-icon class="remove-icon"></hk-times-icon>
                          </span>
                      </div>
                  </div>
              </td>
          </tr>

          <tr>
              {% include "hikster-admin/poi/images-row.html" %}
          </tr>

          <tr>
              <td colspan="2">
                  <div id="map" class="map">
                  </div>
              </td>
          </tr>

          <tr>
            <td colspan="2" class="text-right py-4 no-border">
              <a
                id="btn-cancel"
                class="btn"
                href="{% url 'hikster-admin:poi-list' organization_id=organization.id %}"
                >Cancel</a
              >
              <button @click="save(false)" type="button" class="btn" :disabled="loading">
                {% trans "Save and continue editing" %}
              </button>

              <button
                @click="save(true, true)"
                type="button"
                class="btn"
                :disabled="loading"
              >
                  {% trans "Save and Add new" %}
              </button>
              <button
                @click="save(true)"
                type="button"
                class="btn btn-success"
                :disabled="loading"
              >
                {% trans "Save" %}
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}

{% block body_extra_js %}
    <script>
    var pageMode = "create";
    {% if poi %}
      pageMode = "edit";
    {% endif %}
    </script>

    {% include "website/components/map-scripts.html" %}
    <script src="{% static 'libs/leaflet/dist/leaflet.js' %}"></script>
    <script src="{% static 'libs/leaflet-draw/leaflet.draw.js' %}"></script>
    <script src="{% static 'libs/leaflet.textpath.js' %}"></script>
    <script src="{% static 'libs/leaflet-fullscreen/Control.FullScreen.js' %}"></script>
    <script src="{% static 'libs/leaflet.geometryutil.js' %}"></script>

    {% render_bundle "admin_poi_detail" %}
{% endblock body_extra_js %}

templates/hikster-admin/trail-detail.html
{% extends 'hikster-admin/base_sidebar_authenticated.html' %}

{% load i18n %}
{% load static from staticfiles %}
{% load render_bundle from webpack_loader %}

{% block extra_styles %}
    <style>
    .map {
      width: 100%;
      height: 600px;
    }

    .leaflet-draw-toolbar a {
      background-image: url(/static/img/map/route.png) !important;
      background-size: 25px 25px !important;
      background-position: center !important;
    }
    </style>
    <link rel="stylesheet" href="{% static 'libs/leaflet/dist/leaflet.css' %}" />
    <link rel="stylesheet" href="{% static 'libs/leaflet-draw/leaflet.draw.css' %}" />
    <link rel="stylesheet" href="{% static 'libs/leaflet-fullscreen/Control.FullScreen.css' %}" />
    <link rel="stylesheet" href="{% static 'css/map.css' %}" />
{% endblock extra_styles %}

{% block breadcrumbs %}
    <li class="breadcrumb-item">
        <a href="{% url 'hikster-admin:index' %}">{% trans 'Hikster Admin' %}</a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'hikster-admin:organization' organization_id=organization.id%}">
            {{ organization.name }}
        </a>
    </li>
    <li class="breadcrumb-item">
        <a href="{% url 'hikster-admin:trail-list' organization_id=organization.id %}">
            {% trans "Trails" %}
        </a>
    </li>
    <li class="breadcrumb-item">
        {% if trail %}
            {{ trail.name }}
        {% else %}
            {% trans "Create Trail" %}
        {% endif %}
    </li>
{% endblock %}

{% block content %}

<div>
    {{ graph|json_script:"graph_data" }}
    {{ trail_data|json_script:"trail_data" }}
    {{ trail_shape_geojson|json_script:"trail_shape_geojson" }}
    {{ markers|json_script:"markers_data" }}
    {{ trail_sections_geojson|json_script:"trail_sections_geojson" }}
    {{ activities|json_script:"activities_data" }}
    {{ locations|json_script:"locations_data" }}
    {{ path_types|json_script:"path_types_data" }}
</div>

<div id="trail-detail-component">
  <div class="row justify-content-center">
    <div class="col-12">
      <h1>
        {% if trail %}
          {% trans "Modify Trail" %}
        {% else %}
          {% trans "Create New Trail" %}
        {% endif %}
        <a
          href="{% url 'hikster-admin:trail-new' organization_id=organization.id %}"
          class="btn btn-success float-right"
        >
            {% trans "New" %}
        </a>
      </h1>


      <div v-show="getError('shape_2d')" class="alert alert-danger alert-dismissible fade show d-none" role="alert">
          <strong>{% trans "Error" %}!</strong> {[ getError("shape_2d") ]}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>

      <div v-show="successMessage" class="alert alert-success alert-dismissible fade show d-none" role="alert">
          {[ successMessage ]}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
          </button>
      </div>

      <table class="table">
        <tbody>
          <tr>
            <th scope="row">{% trans "Name" %}</th>
            <td>
              <input
                :class="{ 'form-control': true, 'invalid': getError('name') }"
                type="text"
                v-model="trail.name"
                required
              />
              <div class="invalid-feedback">
                {[ getError("name") ]}
              </div>
            </td>
          </tr>
          <tr>
              <th scope="row">{% trans "Location" %}</th>
              <td>
                <select
                required
                v-model="trail.location"
                :class="{'form-control': true, 'invalid': getError('location')}"
                >
                  <option v-for="location in locations" :value="location.location_id" :key="location.location_id">
                    {[ location.name ]}
                  </option>
                </select>
                <div class="invalid-feedback">
                    {[ getError("location") ]}
                </div>
              </td>
          </tr>
          <tr>
              <td>{% trans "Path Type" %}</td>
              <td>
                  <select v-model="trail.path_type" class="form-control">
                      <option v-for="type in pathTypes" :value="type[0]" :key="type[0]">
                          {[ type[1] ]}
                      </option>
                  </select>
              </td>
          </tr>
          <tr>
              <td>{% trans "Description" %}</td>
              <td>
                  <ckeditor :editor="editor" v-model="trail.description" :config="editorConfig"></ckeditor>
              </td>
          </tr>
          <tr>
              <td>{% trans "Activities" %}</td>
              <td>
                  <div v-for="activity in activities" class="form-group" :key="activity.id">
                      <div class="form-check">
                          <input v-model="activity.selected" type="checkbox" class="form-check-input pointer" :id="'activity' + activity.id">
                          <label class="form-check-label pointer" :for="'activity' + activity.id">
                              {[ activity.name ]}
                          </label>
                      </div>
                  </div>
              </td>
          </tr>


          <tr>
              {% include "hikster-admin/trail/images-row.html" %}
          </tr>

          <tr>
              <td colspan="2">

                  <small v-if="!hasSteps || !pathLayer">
                      {% trans "Note: This Trail does not have valid Trail Sections, you will have to redraw the path to update." %}
                  </small>
                  <div id="map" class="map">
                  </div>
              </td>
          </tr>

          <tr>
            <td colspan="2" class="text-right py-4 no-border">
              <a
                id="btn-cancel"
                class="btn"
                href="{% url 'hikster-admin:trail-list' organization_id=organization.id %}"
                >Cancel</a
              >
              <button @click="save(false)" type="button" class="btn" :disabled="loading">
                {% trans "Save and continue editing" %}
              </button>
              <button
                @click="save(true)"
                type="button"
                class="btn btn-success"
                :disabled="loading"
              >
                {% trans "Save" %}
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock content %}

{% block body_extra_js %}
    <script>
    var pageMode = "create";
    {% if trail %}
      pageMode = "edit";
    {% endif %}
    </script>

    {% include "website/components/map-scripts.html" %}
    <script src="{% static 'libs/leaflet/dist/leaflet.js' %}"></script>
    <script src="{% static 'libs/leaflet-draw/leaflet.draw.js' %}"></script>
    <script src="{% static 'libs/leaflet.textpath.js' %}"></script>
    <script src="{% static 'libs/leaflet-fullscreen/Control.FullScreen.js' %}"></script>
    <script src="{% static 'libs/leaflet.geometryutil.js' %}"></script>
    <script src="{% static 'libs/turfpoints.min.js' %}"></script>

    {% render_bundle "admin_trail_detail" %}
{% endblock body_extra_js %}